name: gdg_campus_connect
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  google_sign_in: ^6.2.1
  
  firebase_storage: ^12.4.9
  firebase_messaging: ^15.0.1
  
  google_generative_ai: ^0.2.0
  provider: ^6.1.2
  equatable: ^2.0.5
  uuid: ^4.4.2
  cloud_firestore: ^5.6.11
  get: ^4.7.2
  intl: ^0.19.0
  cloud_functions: ^5.6.1
  firebase_app_check: ^0.3.2+9


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
